"""Validated domain and agent output contracts."""

from coursepilot.models.contracts import (
    AgentKind,
    Assignment,
    AssignmentResult,
    Course,
    CourseContext,
    DimensionScore,
    IndexStatus,
    MainAgentResult,
    MaterialMetadata,
    MaterialRecord,
    MaterialSearchAttributes,
    MaterialStatus,
    MaterialType,
    NotesResult,
    ReviewResult,
    RevisionMode,
    RevisionResult,
    SourceRef,
    Team,
    TeamMember,
)

__all__ = [
    "AgentKind",
    "Assignment",
    "AssignmentResult",
    "Course",
    "CourseContext",
    "DimensionScore",
    "IndexStatus",
    "MainAgentResult",
    "MaterialMetadata",
    "MaterialRecord",
    "MaterialSearchAttributes",
    "MaterialStatus",
    "MaterialType",
    "NotesResult",
    "ReviewResult",
    "RevisionMode",
    "RevisionResult",
    "SourceRef",
    "Team",
    "TeamMember",
]
